# Este é um arquivo de workflow do GitHub Actions
name: Generate Snake Animation

# Quando este workflow será executado
on:
  schedule:
    # Executa todo dia às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:  # Permite rodar manualmente
  push:               # Roda quando algo for enviado (push) para o repositório

# O que será feito quando o workflow rodar
jobs:
  build:
    runs-on: ubuntu-latest  # Usa um ambiente Ubuntu

    steps:
      # Passo 1: Clonar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Gerar a animação da cobrinha
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Usa seu nome de usuário automaticamente
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Passo 3: Enviar o resultado para a branch atual (commita o SVG)
      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa token automático do GitHub
